#base image to use
FROM ubi8/ubi:8.5
MAINTAINER username <vinhlx90@icloud.com>

#Set the ARG variable NEXUS_VERSION to 2.14.3-02, and set the environment variable NEXUS_HOME to /opt/nexus.
ARG NEXUS_VERSION=2.14.3-02
ENV NEXUS_HOME=/opt/nexus

#Install the java-1.8.0-openjdk-devel package.
RUN yum install -y --setopt=tsflags=nodocs java-1.8.0-openjdk-devel && yum clean all -y

#Run a command to create a nexus user and group. They both have a UID and GID of 1001. Change the permissions of the ${NEXUS_HOME}/ directory to 775.

RUN groupadd -r nexus -f -g 1001 && \
    useradd -u 1001 -r -g nexus -m -d ${NEXUS_HOME} -s /sbin/nologin -c "Nexus User" nexus && \
    chown -R nexus:nexus ${NEXUS_HOME} && chmod -R 755 ${NEXUS_HOME}

#Unpack the nexus-2.14.3-02-bundle.tar.gz file to the ${NEXUS_HOME}/ directory. Add the nexus-start.sh to the same directory.

ADD nexus-${NEXUS_VERSION}-bundle.tar.gz ${NEXUS_HOME}
ADD nexus-start.sh ${NEXUS_HOME}/

#Run a command, ln -s ${NEXUS_HOME}/nexus-${NEXUS_VERSION} ${NEXUS_HOME}/nexus2, to create a symlink in the container. Run a command to recursively change the ownership of the Nexus home directory to nexus:nexus.
RUN ln -s ${NEXUS_HOME}/nexus-${NEXUS_VERSION} ${NEXUS_HOME}/nexus2

#Make the container run as the nexus user, and set the working directory to /opt/nexus
WORKDIR ${NEXUS_HOME}
USER nexus

#Define a volume mount point for the /opt/nexus/sonatype-work container directory. The Nexus server stores data in this directory.
VOLUME ["/opt/nexus/sonatype-work"]

#Set the default container command to nexus-start.sh.
CMD ["sh", "nexus-start.sh"]
