warning: Cannot check if git requires authentication.
apiVersion: v1
items:
- apiVersion: image.openshift.io/v1
  kind: ImageStream
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    labels:
      app: hello-world
      app.kubernetes.io/component: hello-world
      app.kubernetes.io/instance: hello-world
    name: hello-world
  spec:
    lookupPolicy:
      local: false
  status:
    dockerImageRepository: ""
- apiVersion: build.openshift.io/v1
  kind: BuildConfig
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    labels:
      app: hello-world
      app.kubernetes.io/component: hello-world
      app.kubernetes.io/instance: hello-world
    name: hello-world
  spec:
    nodeSelector: null
    output:
      to:
        kind: ImageStreamTag
        name: hello-world:latest
    postCommit: {}
    resources: {}
    source:
      git:
        uri: https://github.com/vinhlx90/DO188-apps/nodejs-helloworld
      type: Git
    strategy:
      sourceStrategy:
        from:
          kind: ImageStreamTag
          name: nodejs:16-ubi8
          namespace: openshift
      type: Source
    triggers:
    - github:
        secret: 5jTXLYfRJR7BZT7CI172
      type: GitHub
    - generic:
        secret: CSorDa_66x9z-a2RFikZ
      type: Generic
    - type: ConfigChange
    - imageChange: {}
      type: ImageChange
  status:
    lastVersion: 0
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    annotations:
      image.openshift.io/triggers: '[{"from":{"kind":"ImageStreamTag","name":"hello-world:latest"},"fieldPath":"spec.template.spec.containers[?(@.name==\"hello-world\")].image"}]'
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    labels:
      app: hello-world
      app.kubernetes.io/component: hello-world
      app.kubernetes.io/instance: hello-world
    name: hello-world
  spec:
    replicas: 1
    selector:
      matchLabels:
        deployment: hello-world
    strategy: {}
    template:
      metadata:
        annotations:
          openshift.io/generated-by: OpenShiftNewApp
        creationTimestamp: null
        labels:
          deployment: hello-world
      spec:
        containers:
        - image: ' '
          name: hello-world
          ports:
          - containerPort: 8080
            protocol: TCP
          resources: {}
  status: {}
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    labels:
      app: hello-world
      app.kubernetes.io/component: hello-world
      app.kubernetes.io/instance: hello-world
    name: hello-world
  spec:
    ports:
    - name: 8080-tcp
      port: 8080
      protocol: TCP
      targetPort: 8080
    selector:
      deployment: hello-world
  status:
    loadBalancer: {}
kind: List
metadata: {}
